name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.0
          
      - name: Generate help tags
        run: |
          nvim --headless -u NONE -c "helptags doc/" -c "q"
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/tags
          git commit -m "chore(docs): update help tags" || echo "No changes to commit"
          git push
